import { rand } from '@vueuse/core';
import type { ValueOf } from 'element-plus/es/components/table/src/table-column/defaults';
import type { RootObject, CodeInfo } from '@/types';

export const mockData: RootObject = {
  pageNum: 1,
  totalPages: 1,
  errorMsg: 'dolor nulla aute ipsum',
  result: 'eiusmod dolore consequat deserunt',
  pageSize: 17,
  codeInfos: [
    {
      fdppm: 92,
      createDate: '1972-01-03',
      sampleStatus: true,
      deliveryStatus: 'laborum reprehenderit exercitation elit',
      iqcTestItems: 'veniam elit sit',
      productLines: [
        {
          manufacturer: 'sit in',
          updateDate: '1981-01-19',
          subProductLine: 'aute',
          createDate: '1994-04-29',
          codeId: 68,
          materialOwner: 'in Excepteur magna Lorem et',
          updater: 'eu in adipisicing Lorem ipsum',
          year: 'est',
          productLine: 'laborum',
          code: '26',
          id: 3,
          creator: 'ea consectetur amet quis',
        },
        {
          updateDate: '1988-01-01',
          id: 33,
          productLine: 'deserunt ipsum minim Ut mollit',
          subProductLine: 'quis aliqua anim cupidatat',
          manufacturer: 'anim',
          year: 'ut',
          createDate: '2015-07-13',
          codeId: 29,
          updater: 'commodo est',
          materialOwner: 'Lorem consectetur laboris',
          creator: 'magna',
          code: '13',
        },
      ],
      priority: 'cupidatat',
      progress: {
        manufacturer: 'culpa elit pariatur reprehenderit cupidatat',
        updater: 'Lorem',
        updateDate: '2005-03-29',
        code: '66',
        creator: 'magna aliqua mollit officia consectetur',
        hardwareProgress: 'consectetur sint Lorem',
        createDate: '2009-08-30',
        codeId: 7,
        purchaseProgress: 'in cillum irure',
        id: 40,
        year: 'Excepteur voluptate in',
        overallProgress: 'laborum',
        softwareProgress: 'eu ad',
      },
      finishedDate: '1989-05-02',
      manufacturer: 'voluptate proident',
      updateDate: '1980-03-14',
      iqcOwner: 'sunt Lorem sit',
      codeMaturity: '46',
      newDev: false,
      updater: 'aliqua aute cillum',
      planDate: '2020-01-09',
      manufacturerAteCapability: false,
      code: '95',
      datasheetReady: true,
      productLine: 'aliqua eu aute',
      ateCapabilityId: 13,
      mqeOwner: 'aliquip adipisicing reprehenderit',
      codeDesc: '76',
      packageInfo: 'commodo eiusmod laborum irure',
      creator: 'voluptate dolor fugiat cillum Ut',
      spotCode: '45',
      iqcCovered: false,
      category: 'occaecat amet esse proident dolor',
      owner: 'esse',
      subCategory: 'fugiat',
      id: 4,
      ateCapability: 'cillum',
      bcmClassification: 'commodo exercitation dolore',
      manufacturerOqcCapability: true,
      year: 'velit ullamco amet',
      subCode: '84',
      notDevReason: 'aliquip dolor dolor laborum',
      subProductLine: 'sed in',
      region: 'tempor',
      deviceOwner: 'in',
    },
    {
      category: 'sed dolore labore enim',
      year: 'eu aliquip ut elit',
      updateDate: '1984-11-13',
      code: '38',
      manufacturerAteCapability: false,
      codeMaturity: '37',
      newDev: true,
      mqeOwner: 'ut mollit sunt',
      ateCapability: 'enim Ut ea voluptate in',
      datasheetReady: false,
      spotCode: '77',
      subCategory: 'exercitation',
      deviceOwner: 'velit anim cillum',
      finishedDate: '2011-06-16',
      iqcCovered: false,
      packageInfo: 'Lorem pariatur',
      productLines: [
        {
          codeId: 25,
          productLine: 'esse ad',
          updater: 'Lorem sed est do',
          updateDate: '1975-04-14',
          manufacturer: 'id irure esse',
          id: 27,
          creator: 'deserunt pariatur',
          year: 'non dolor occaecat sit cupidatat',
          createDate: '2007-02-23',
          code: '86',
          materialOwner: 'cupidatat',
          subProductLine: 'in officia commodo eiusmod est',
        },
        {
          manufacturer: 'cillum officia esse',
          materialOwner: 'est aliqua esse dolore',
          updater: 'aliquip proident dolore reprehenderit nulla',
          updateDate: '2010-09-10',
          code: '85',
          id: 19,
          productLine: 'aliquip',
          createDate: '1989-11-01',
          codeId: 56,
          year: 'in',
          subProductLine: 'eiusmod qui consectetur nostrud dolore',
          creator: 'irure qui eu Lorem ipsum',
        },
        {
          updater: 'in',
          id: 12,
          subProductLine: 'culpa',
          updateDate: '2005-01-10',
          materialOwner: 'quis irure adipisicing anim',
          productLine: 'dolor',
          codeId: 10,
          creator: 'cillum non mollit ut exercitation',
          year: 'eiusmod dolore incididunt',
          createDate: '1974-03-02',
          manufacturer: 'pariatur aliquip amet sint ullamco',
          code: '38',
        },
        {
          subProductLine: 'elit proident Ut',
          codeId: 95,
          year: 'magna tempor sunt quis',
          createDate: '1991-09-02',
          productLine: 'ipsum pariatur eu dolore ex',
          id: 10,
          materialOwner: 'qui sint ad',
          manufacturer: 'pariatur',
          creator: 'deserunt laboris',
          updater: 'cillum',
          code: '38',
          updateDate: '1971-08-06',
        },
      ],
      progress: {
        updateDate: '1995-04-22',
        overallProgress: 'deserunt nostrud anim adipisicing ullamco',
        creator: 'adipisicing nostrud laboris in',
        id: 62,
        year: 'sed culpa do ad',
        purchaseProgress: 'eu qui',
        softwareProgress: 'sed cillum tempor elit',
        updater: 'ea velit proident voluptate Ut',
        code: '22',
        codeId: 56,
        manufacturer: 'sint ut mollit elit laboris',
        hardwareProgress: 'elit qui labore cupidatat consequat',
        createDate: '1972-07-31',
      },
      id: 16,
      subProductLine: 'exercitation dolor esse',
      deliveryStatus: 'cupidatat amet incididunt tempor occaecat',
      owner: 'proident consectetur',
      createDate: '2005-07-04',
      iqcOwner: 'enim et dolor',
      subCode: '90',
      updater: 'consectetur sunt',
      manufacturer: 'anim fugiat proident enim ipsum',
      priority: 'exercitation officia',
      sampleStatus: false,
      fdppm: 2,
      notDevReason: 'pariatur',
      manufacturerOqcCapability: false,
      planDate: '2009-07-26',
      region: 'nulla',
      iqcTestItems: 'in labore in anim',
      creator: 'esse',
      productLine: 'velit enim ex et',
      ateCapabilityId: 14,
      codeDesc: '12',
      bcmClassification: 'elit',
    },
    {
      datasheetReady: false,
      packageInfo: 'eu aliqua quis ut magna',
      spotCode: '55',
      manufacturer: 'Excepteur cillum qui incididunt',
      owner: 'aliquip ut eu',
      creator: 'nulla Ut quis consectetur eiusmod',
      mqeOwner: 'magna',
      manufacturerOqcCapability: true,
      codeDesc: '37',
      progress: {
        updater: 'culpa esse',
        softwareProgress: 'cillum nostrud ipsum tempor Ut',
        creator: 'Duis officia velit esse in',
        overallProgress: 'ut Lorem culpa',
        purchaseProgress: 'Duis velit',
        updateDate: '1994-11-13',
        code: '88',
        manufacturer: 'amet magna cillum deserunt elit',
        year: 'nostrud voluptate mollit',
        createDate: '1978-04-19',
        id: 87,
        hardwareProgress: 'sed ut',
        codeId: 37,
      },
      year: 'sit in exercitation',
      manufacturerAteCapability: false,
      iqcOwner: 'ad sunt esse',
      ateCapabilityId: 25,
      code: '90',
      region: 'nisi fugiat aliqua',
      planDate: '1997-06-08',
      id: 13,
      sampleStatus: false,
      updater: 'anim esse quis',
      subProductLine: 'pariatur exercitation',
      createDate: '2021-03-04',
      subCode: '9',
      productLines: [
        {
          productLine: 'nostrud Excepteur sunt laborum irure',
          subProductLine: 'sint dolore in ex aute',
          updater: 'anim dolore elit labore',
          updateDate: '1989-10-08',
          codeId: 3,
          code: '98',
          manufacturer: 'deserunt anim Excepteur',
          materialOwner: 'sint sit quis sunt',
          id: 41,
          year: 'ex',
          creator: 'id',
          createDate: '1973-07-01',
        },
        {
          year: 'fugiat dolore occaecat',
          subProductLine: 'id laboris',
          updater: 'laboris ut est in cillum',
          updateDate: '2010-12-05',
          createDate: '1980-09-21',
          creator: 'ad Lorem',
          code: '17',
          materialOwner: 'esse laborum',
          codeId: 98,
          manufacturer: 'aliqua',
          productLine: 'ex',
          id: 19,
        },
        {
          createDate: '2018-08-29',
          materialOwner: 'ipsum et',
          subProductLine: 'ipsum cupidatat enim',
          productLine: 'Lorem reprehenderit est',
          id: 72,
          manufacturer: 'pariatur',
          updater: 'sed esse do anim',
          updateDate: '1984-03-07',
          code: '27',
          year: 'sit voluptate',
          creator: 'tempor voluptate est ex quis',
          codeId: 88,
        },
        {
          creator: 'do',
          manufacturer: 'quis irure pariatur non ad',
          updater: 'ea aute consequat non',
          productLine: 'dolor',
          createDate: '1990-05-08',
          updateDate: '1973-08-23',
          code: '55',
          id: 32,
          codeId: 73,
          materialOwner: 'non',
          year: 'veniam commodo ut',
          subProductLine: 'dolore elit magna',
        },
      ],
      codeMaturity: '42',
      deliveryStatus: 'ut et reprehenderit',
      updateDate: '1980-11-20',
      newDev: false,
      notDevReason: 'dolor aliquip exercitation',
      finishedDate: '1981-11-28',
      ateCapability: 'dolore officia cupidatat irure',
      category: 'voluptate tempor officia',
      deviceOwner: 'laboris mollit cupidatat sed',
      fdppm: 26,
      subCategory: 'fugiat',
      iqcCovered: false,
      priority: 'eiusmod labore Excepteur officia',
      bcmClassification: 'nisi eiusmod',
      productLine: 'velit',
      iqcTestItems: 'laborum enim',
    },
  ],
};
export const getShowData = () => {
  const showData: RootObject = {
    pageNum: 1,
    totalPages: 1,
    errorMsg: 'dolor nulla aute ipsum',
    result: 'eiusmod dolore consequat deserunt',
    pageSize: 17,
    codeInfos: [],
  };
  type NeedKeyList = keyof CodeInfo;
  const needKeyList: Array<NeedKeyList> = [
    'id',
    'year',
    'code',
    'subCode',
    'codeDesc',
    'category',
    'subCategory',
    'manufacturer',
    'planDate',
    'owner',
    'deliveryStatus',
    'createDate',
    'creator',
    'updateDate',
    'updater',
    'productLines',
    'progress',
  ];
  mockData.codeInfos.forEach((x) => {
    const data: Record<NeedKeyList, any> = {} as CodeInfo;
    needKeyList.forEach((needKey) => {
      data[needKey] = x[needKey];
    });
    showData.codeInfos?.push(data);
  });
  return showData;
};
let innerGenRandomCodeInfosDataCount = 0;
const genRandomCodeInfosData = () => {
  const baseData: Partial<CodeInfo> = {};

  baseData.id = innerGenRandomCodeInfosDataCount;
  innerGenRandomCodeInfosDataCount += 1;

  baseData.year = `${rand(2000, 2022)}`;

  const code = Array(8)
    .map(() => rand(0, 9))
    .join('');
  baseData.code = code;
  baseData.subCode = code.slice(0, 4);
};
export const genRandomData = () => {
  const baseData: Partial<RootObject> = {
    pageNum: 1,
    totalPages: 1,
    errorMsg: 'dolor nulla aute ipsum',
    result: 'eiusmod dolore consequat deserunt',
    pageSize: 17,
    codeInfos: [],
  };
};
